import { type Content, type Lang } from '../types';

const FILES_BASE = '/shows/marita/files';

const RU_CONTENT: Content = {
  title: 'Колдовство Мариты',
  seoSubtitle:
    'Яркая и теплая многослойная история, с захватывающим сюжетом: сказка и философия, смех и печаль, смерть и любовь в обрамлении живой сефардской музыки, авторских кукол и декораций.',
  heroSecondary:
    'С двумя чемоданами удивительных предметов театр приедет к вам в гости и привезёт настоящее волшебство в детский сад, школу, студию и даже квартиру.\nЭто спектакль для всей семьи, интересный по-разному детям примерно с 6 лет, подросткам и родителям.',
  teaserVideoUrl: 'https://www.youtube.com/embed/X5kZOSKk6z0',
  heroBadge: 'Кукольный мюзикл с живой музыкой и песнями',
  theatreLabel: 'Театр «Рыба Кива»',
  theatreSubtitle: 'Волшебный спектакль для всей семьи на Пурим!',
  menuInvite: 'Пригласить театр',
  menuAbout: 'О спектакле',
  menuSchedule: 'Афиша',
  menuMedia: 'Видео и фото',
  menuTeam: 'Команда',
  sectionAbout: 'Подробнее о спектакле',
  sectionFlyer: 'Флаер',
  sectionPoster: 'Афиша',
  sectionSchedule: 'Расписание спектаклей',
  sectionTeaser: 'Видео-тизер',
  sectionFragments: 'Видео с фрагментами',
  sectionPhotos: 'Фотографии',
  sectionTeam: 'Команда спектакля',
  sectionContact: 'Контакты',
  sectionDownloads: 'Скачать материалы',
  flyerDownload: 'Скачать флаер',
  posterDownload: 'Скачать афишу',
  photosDownload: 'Скачать фото-пакет',
  posterImage: `${FILES_BASE}/poster.jpg`,
  posterPdf: `${FILES_BASE}/poster.pdf`,
  flyerPdf: `${FILES_BASE}/flyer-kozocka-zlata-ru.pdf`,
  photosArchive: `${FILES_BASE}/photos-kozocka-zlata-ru.zip`,
  aboutText: `Замок, король, принцесса, волшебство, все как положено, и, казалось бы, сказка должна катиться себе и катиться по рельсам классического сюжета старинной сефардской легенды о принцессе, бедном юноше, злой мачехе и любви.
Но в спектакле «Колдовство Мариты» мы посмотрим на архетипическую историю с неожиданной стороны и вместе со зрителями попытаемся разобраться: что же такое эта любовь, побеждающая смерть?
Чудо, волшебство, колдовство, а может — плод самоотверженного и чистого сердца?
Дети успеют посмеяться, чуть-чуть испугаться, почти заплакать и обрадоваться счастливому финалу.
А взрослым будет о чём поговорить с детьми. И кто знает — может быть, задуматься самим?`,
  contactText:
    'Чтобы пригласить спектакль к вам в гости, напишите нам в WhatsApp. Расскажите, для кого вы планируете показ, и мы подберём удобную дату и формат.',
  contactWhatsappLabel: 'Написать в WhatsApp',
  ageLabel: 'Возраст',
  durationLabel: 'Продолжительность',
  formatLabel: 'Формат',
  infoAgeValue: 'с 6 лет и старше',
  infoDurationValue: '1 час 20 минут',
  infoFormatValue: 'Для взрослых в присутствии детей 🙂',
  faqTitle: 'Частые вопросы',
  faqItems: [
    {
      q: 'Что нужно, чтобы пригласить спектакль к себе?',
      a: 'Для показа спектакля нужен небольшой зал, студия или школьный класс с возможностью затемнения. Напишите нам в вотсапп и мы согласуем детали.',
    },
    {
      q: 'Можно ли показывать спектакль в большом театральном зале?',
      a: 'Теоретически спектакль можно играть и на большой сцене, у нас был такой опыт. Но лучше всего он звучит в камерной атмосфере, когда зрители расположены прямо напротив центра сцены, с размахом не более 4 метров. Идеально, если детей можно посадить ближе и ярусно — например, на подушки или коврики.',
    },
    {
      q: 'Нужно ли для приезда спектакля специальное оборудование?',
      a: 'Нужны затемнение, розетка 220V и свободное пространство перед зрителями. Всё остальное — свет, звук, куклы и декорации — мы привозим с собой.',
    },
    {
      q: 'Можно ли прийти с малышом, младше указанного возраста?',
      a: 'Мы рекомендуем спектакль детям с 6 лет. Вы можете привести ребёнка младше, но, пожалуйста, оставайтесь рядом и обращайте внимание на его состояние: чтобы ему не было страшно, скучно или слишком утомительно. В крайнем случае всегда можно ненадолго выйти из зала, чтобы не мешать другим зрителям.',
    },
    {
      q: 'Можно ли оставить ребенка одного на спектакле?',
      a: 'Начиная примерно с 9 лет ребёнка уже можно оставить на спектакле одного. Но для нас очень важно, чтобы большинство родителей тоже были в зале — и дело не в дисциплине. Многие смысловые и эмоциональные обертона спектакля обращены именно к взрослым, и когда рядом нет тех, кому их адресовать, нам по-настоящему грустно. Мы искренне верим, что спектакль станет общим переживанием и темой для последующих разговоров для всей вашей семьи.',
    },
    {
      q: 'Нужно ли взрослым покупать билет?',
      a: 'Да, билет нужен каждому зрителю.',
    },
    {
      q: 'Возврат билетов',
      a: 'Вы можете вернуть билет не позднее 7 дней до мероприятия (за вычетом 5% которые берет платежная система за транзакцию). Позже этого срока билет можно только перенести на любое другое из мероприятий театра, где будут свободные места.',
    },
    {
      q: 'Можно ли купить билет перед спектаклем за наличные?',
      a: 'Билет перед спектаклем за наличные можно купить всегда, когда есть свободные места. Однако, как правило, билеты, купленные заранее, стоят дешевле.',
    },
    {
      q: 'Можно ли получить скидку?',
      a: 'Если вы находитесь в сложном финансовом положении или у вас многодетная семья и вы покупаете много билетов, напишите нам в WhatsApp и мы что-нибудь придумаем.',
    },
  ],
  teamAuthorTitle: 'Автор проекта и сценария',
  teamAuthorName: 'Елена Шамис',
  songsTitle: 'Песни',
  songsName: 'Елена Шамис и Михаил Стародубцев',
  teamDirectorTitle: 'Художники',
  teamDirectorName: 'Ольга Филлипова и Варвара Даревская',
  masterTitle: 'Изготовление сложных декораций',
  masterName: 'Михаил Стародубцев',
  teamActorsTitle: 'Актёры',
  teamActors: [
    { name: 'Мария Гескина', role: 'гитара, вокал, работа с куклами' },
    { name: 'Михаил Стародубцев', role: 'гитара, вокал, работа с куклами' },
    { name: 'Саша Скворцова', role: 'скрипка, работа с куклами' },
    { name: 'Елена Шамис', role: 'вокал, работа с куклами' },
  ],
  photoDownloadLabel: 'Скачать',
  carouselOpenLabel: 'Открыть крупнее',
  carouselDownloadLabel: 'Скачать фото',
  carouselPrevLabel: 'Предыдущее фото',
  carouselNextLabel: 'Следующее фото',
  carouselCloseLabel: 'Закрыть',
  scheduleDateLabel: 'Дата',
  scheduleTimeLabel: 'Время',
  schedulePlaceLabel: 'Место',
  scheduleFormatLabel: 'Комментарий',
  scheduleLanguageLabel: 'Язык',
  scheduleRows: [
    {
      date: '28 ноября',
      time: '09:00',
      place: 'Иерусалим, школа',
      format: 'Закрытый показ',
      language: 'Иврит',
    },
    {
      date: '09 декабря',
      time: '18:00',
      place: 'Иерусалим, Матнас Гило',
      format: 'Закрытый показ',
      language: 'Русский',
    },
    {
      date: '11 декабря',
      time: '17:00',
      place: 'Нагария',
      format: 'Открытый показ',
      language: 'Русский',
    },
    {
      date: '18 декабря',
      time: '18:00',
      place: 'Хайфа, фестиваль «В Чемодане»',
      format: 'Открытый показ',
      language: 'Иврит',
    },
    {
      date: '19 декабря',
      time: '11:00',
      place: 'Хайфа, Матнас Адар',
      format: 'Открытый показ',
      language: 'Русский',
    },
    {
      date: '21 декабря',
      time: '17:00',
      place: 'Хайфа',
      format: 'Открытый показ',
      language: 'Иврит',
    },
  ],
};

const EN_CONTENT: Content = {
  title: 'The Magic of Marita',
  seoSubtitle:
    'A vivid, warm, multilayered story with a captivating plot — part fairy tale, part philosophical journey; filled with laughter and sorrow, death and love, and brought to life through live Sephardic music, original puppets, and handcrafted sets.',
  heroSecondary:
    'With two suitcases full of strange and wonderful objects, Ryba Kiva Theatre can bring the performance to your school, kindergarten, studio, community space, or even your home.',
  teaserVideoUrl: 'https://www.youtube.com/embed/X5kZOSKk6z0',
  heroBadge: 'A puppet musical with live music and original songs',
  theatreLabel: 'Ryba Kiva Theatre',
  theatreSubtitle: 'A magical family performance for Purim!',
  menuInvite: 'Invite the theatre',
  menuAbout: 'About the show',
  menuSchedule: 'Shows',
  menuMedia: 'Video & photos',
  menuTeam: 'Team',
  sectionAbout: 'About the show',
  sectionFlyer: 'Flyer',
  sectionPoster: 'Poster',
  sectionSchedule: 'Performance schedule',
  sectionTeaser: 'Teaser video',
  sectionFragments: 'Video excerpts',
  sectionPhotos: 'Photos',
  sectionTeam: 'Creative team',
  sectionContact: 'Contact',
  sectionDownloads: 'Downloads',
  flyerDownload: 'Download flyer',
  posterDownload: 'Download poster',
  photosDownload: 'Download photo pack',
  posterImage: `${FILES_BASE}/poster.jpg`,
  posterPdf: `${FILES_BASE}/poster.pdf`,
  flyerPdf: `${FILES_BASE}/flyer-kozocka-zlata-ru.pdf`,
  photosArchive: `${FILES_BASE}/photos-kozocka-zlata-ru.zip`,
  aboutText: `A castle, a king, a princess, magic — everything is just as it should be. It seems the story could simply follow the familiar path of an old Sephardic legend about a princess, a poor young man, a wicked stepmother, and love.
    But in The Magic of Marita, we look at this archetypal tale from an unexpected angle. Together with the audience, we try to understand: what kind of love is strong enough to conquer death?
    Is it a miracle, magic, sorcery — or perhaps the work of a selfless and pure heart?
    Children will laugh, get a little frightened, almost cry, and rejoice in the happy ending.
    And adults will leave with something to talk about with the children — and perhaps something to ponder themselves.`,
  contactText:
    'To invite the performance to your venue, write to us on WhatsApp. Tell us who the audience will be and we will suggest a convenient date and format.',
  contactWhatsappLabel: 'Message us on WhatsApp',
  ageLabel: 'Age',
  durationLabel: 'Duration',
  formatLabel: 'Format',
  infoAgeValue: 'Recommended for ages 6+',
  infoDurationValue: '1 hour 20 minutes',
  infoFormatValue: 'Best enjoyed by children and adults together',
  faqTitle: 'FAQ',
  faqItems: [
    {
      q: 'What do we need to host the show?',
      a: 'A small hall, studio or classroom that can be darkened. Send us a WhatsApp message and we will coordinate the details.',
    },
    {
      q: 'Can you perform in a large theatre hall?',
      a: 'It is possible — we have done it — but the performance feels best in an intimate setting with the audience no farther than about four metres from the screen and kids seated close on cushions or risers.',
    },
    {
      q: 'Do you require any special equipment?',
      a: 'We only need partial darkness, a 220V socket and free space in front of the audience. Everything else — lighting, sound, puppets, and set pieces — we bring with us.',
    },
    {
      q: 'Can we bring younger children under four?',
      a: 'We recommend the performance from ages 4–5, ideally from 6. You may bring a younger child, just stay nearby and watch if the experience feels comfortable, and step out briefly if needed.',
    },
    {
      q: 'Can children attend without parents?',
      a: 'From about age nine they can, but we truly love when adults are in the room: many emotional nuances are addressed to you, so the performance becomes a shared family experience.',
    },
    {
      q: 'Do adults need a ticket?',
      a: 'Yes, every audience member needs a ticket.',
    },
    {
      q: 'Ticket refunds',
      a: 'You can return a ticket no later than 7 days before the event (minus a 5% payment-system transaction fee). After that deadline, the ticket can only be transferred to any other performance by the theatre where seats are available.',
    },
    {
      q: 'Can I buy a ticket for cash before the show?',
      a: 'You can always buy a ticket for cash before the performance when seats are available. However, tickets purchased in advance are usually cheaper.',
    },
    {
      q: 'Can I get a discount?',
      a: 'If you are in a difficult financial situation or you have a large family and are buying many tickets, write to us on WhatsApp and we will work something out.',
    },
  ],
  teamAuthorTitle: 'Creator and scriptwriter',
  teamAuthorName: 'Elena Shamis',
  songsTitle: 'Songs',
  songsName: 'Elena Shamis and Mikhail Starodubtsev',
  teamDirectorTitle: 'Designers',
  teamDirectorName: 'Olga Filippova and Varvara Darevskaya',
  masterTitle: 'Complex set construction',
  masterName: 'Mikhail Starodubtsev',
  teamActorsTitle: 'Cast',
  teamActors: [
    { name: 'Maria Geskina', role: 'guitar, vocals, puppetry' },
    { name: 'Mikhail Starodubtsev', role: 'guitar, vocals, puppetry' },
    { name: 'Sasha Skvortsova', role: 'violin, puppetry' },
    { name: 'Elena Shamis', role: 'vocals, puppetry' },
  ],
  photoDownloadLabel: 'Download',
  carouselOpenLabel: 'View larger',
  carouselDownloadLabel: 'Download photo',
  carouselPrevLabel: 'Previous photo',
  carouselNextLabel: 'Next photo',
  carouselCloseLabel: 'Close',
  scheduleDateLabel: 'Date',
  scheduleTimeLabel: 'Time',
  schedulePlaceLabel: 'Venue',
  scheduleFormatLabel: 'Comment',
  scheduleLanguageLabel: 'Language',
  scheduleRows: [
    {
      date: '28 ноября',
      time: '09:00',
      place: 'Иерусалим, школа',
      format: 'Закрытый показ',
      language: 'Иврит',
    },
    {
      date: '09 декабря',
      time: '18:00',
      place: 'Иерусалим, Матнас Гило',
      format: 'Закрытый показ',
      language: 'Русский',
    },
    {
      date: '11 декабря',
      time: '17:00',
      place: 'Нагария',
      format: 'Открытый показ',
      language: 'Русский',
    },
    {
      date: '18 декабря',
      time: '18:00',
      place: 'Хайфа, фестиваль «В Чемодане»',
      format: 'Открытый показ',
      language: 'Иврит',
    },
    {
      date: '19 декабря',
      time: '11:00',
      place: 'Хайфа, Матнас Адар',
      format: 'Открытый показ',
      language: 'Русский',
    },
    {
      date: '21 декабря',
      time: '17:00',
      place: 'Хайфа',
      format: 'Открытый показ',
      language: 'Иврит',
    },
  ],
};

export const MARITA_CONTENT: Partial<Record<Lang, Content>> = {
  ru: RU_CONTENT,
  en: EN_CONTENT,
};
